### PR TITLE
log-log combined spectrum autoscaling plot

### PR DESCRIPTION
**Pull request by thomasballinger**
This version of the plot that autocales the logarithmic x axis isn't great. If it makes sense to hard code the Hz min and max then this is easy. If not, read on:

uPlots snapping of x axis scale to powers of the base used combined with my mediocre data ingestion rate measure make this plot hard to read because the xMax and xMin jump around by a significant amount. uPlot also doesn't allow updates to a log x scale so I had to break outside the abstraction I so confidently crafted yesterday, recreating the plot 10 times a second instead of calling update functions on it.

If this is better than the linear-linear version we can swap it in, or I can hack around this by making the xMax and yMin sticky somehow. I figured I'd wait to hear what we really want from a log-log spectrum before I spend any time on a hack, and I might look into forking uPlot on my own time to add it if it makes sense.

Again, hardcoding the limits of the x axis is the easiest thing to do, but if sensors send data at very different rates it seems like a shame to miss a bunch of frequencies or waste space on the chart as the Nyquist frequency moves up and down for different sensors.

https://raw.githack.com/twinleaf/twinleaf-web-ui/bdfb2af97ecf608cdc4ae2c4b1329e08e7e847a4/web/index.html

https://user-images.githubusercontent.com/458879/147799713-8a4bcbb8-1cac-4f96-8b9c-5a1980d5e9b9.mov

### CODE REVIEW

**Comment by leeoniya** [comment]
> and I might look into forking uPlot on my own time to add it if it makes sense.

once you figure out how you want it to behave, it's probably worth opening an issue in the uPlot repo before resorting to the nuclear option ;)

you can fully implement your own `scales.x.range` and `scales.y.range` to skip uPlot's auto-ranging logic. if you leave `scale.y.auto: true` uPlot will still auto-find the data's min/max and pass those to your ranging function.

log10 scales have a way to only snap to full powers of 10 which would stabilize it somewhat, but i see you're using log2 in the vid, so that wont work here.

**Comment by thomasballinger** [comment]
@leeoniya thanks for noticing this, and happy new year! I thought I'd fork to investigate + hack it without wasting your time then hope to contribute, but the ship has sailed on understanding the problem more before you heard my complaint :)

I thought I was seeing snapping to full powers of 2 as well, which I didn't want because it caused bigger jumps. I'll look into this and open zero to three issues: setScale not working for a log2 x, adding a non-snapping behavior for auto range on log x, and getting the auto range to work for log2. I'm betting zero because I just didn't understand these yet!

Thanks for the pointer and thanks for making uPlot.

**Comment by leeoniya** [comment]
> without wasting your time then hope to contribute, but the ship has sailed on understanding the problem more before you heard my complaint :)

just gives me an excuse to document some poorly documented things in the form of issue responses. also your coffee/month donation entitles you to more "time wasting" than most ;)

> I thought I was seeing snapping to full powers of 2 as well

well it definitely snaps to powers of 2, but log10 snaps to powers-of-10 * N by default, where N is integers 1..9, so e.g. 100, 200, 300.

happy new year to you, too! (still another 3h of 2021 left for me).

**Comment by thomasballinger** [comment]
Quick update, both supposed bugs are not real: setScale() works fine for a log2 x and auto range works fine for log2 x. If I want the non-snapping behavior I'll open an issue to discuss, but the pointer to log10 snapping to powers-of-10 * N gets this close enough for now. Thanks!

**Comment by thomasballinger** [comment]
Oh beautiful, and as you said implementing my own scales.x.range gives me that. I'm all set!

**Comment by thomasballinger** [comment]
This works fine now. The spectrum still needs to be reworked with some signal processing magic, unrelated to the plotting.

https://user-images.githubusercontent.com/458879/147845080-1534e3ba-fd49-4575-a48d-63f079bcc56b.mov

**Pull request merged**
